// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'logo': string;
  'logoDivider': string;
  'signInForm': string;
  'signInFormButton': string;
  'signInFormItem': string;
  'signInHeader': string;
  'signInItem': string;
}
export const cssExports: CssExports;
export default cssExports;
