// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'headerAlt': string;
  'headerTitle': string;
  'logo': string;
  'logoDivider': string;
  'page': string;
  'signUpForm': string;
  'signUpFormButton': string;
  'signUpFormItem': string;
  'signUpHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
