// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'formButton': string;
  'formItem': string;
  'header': string;
  'headerAlt': string;
  'headerTitle': string;
  'logo': string;
  'logoDivider': string;
  'mainForm': string;
  'page': string;
}
export const cssExports: CssExports;
export default cssExports;
