apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: bridge-mapping
  labels:
    svc: bridge
spec:
  hostname: "*"
  prefix: /control/
  service: bridge.fennel:2475

---

apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: control-host
spec:
  hostname: "*"
  mappingSelector:
    matchLabels:
      svc: bridge
  requestPolicy:
    insecure:
      action: Route
