apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: data-server-mapping
  labels:
    svc: go-http
spec:
  hostname: "*"
  prefix: /data/
  service: http-server.fennel:2425

---

apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: data-host
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-cert
  tls:
    min_tls_version: v1.2
    alpn_protocols: h2
  mappingSelector:
    matchLabels:
      svc: go-http
  requestPolicy:
    insecure:
      action: Route
