// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'logoAndName': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
