// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'membersCount': string;
  'nameAndCount': string;
  'teamContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
