// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footnote': string;
  'tierContainer': string;
  'tierTable': string;
  'tierTableLabel': string;
  'tierTableValue': string;
  'tierTitle': string;
  'tierURL': string;
  'tierURLContainer': string;
  'tierURLIcon': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
