// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footnote': string;
  'status': string;
  'statusDot': string;
  'tierContainer': string;
  'tierTable': string;
  'tierTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
