// Code generated by capnpc-go. DO NOT EDIT.

package rpc

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type NitrousBinlogEvent capnp.Struct

// NitrousBinlogEvent_TypeID is the unique identifier for the type NitrousBinlogEvent.
const NitrousBinlogEvent_TypeID = 0xd484e90b6960c0da

func NewNitrousBinlogEvent(s *capnp.Segment) (NitrousBinlogEvent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return NitrousBinlogEvent(st), err
}

func NewRootNitrousBinlogEvent(s *capnp.Segment) (NitrousBinlogEvent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return NitrousBinlogEvent(st), err
}

func ReadRootNitrousBinlogEvent(msg *capnp.Message) (NitrousBinlogEvent, error) {
	root, err := msg.Root()
	return NitrousBinlogEvent(root.Struct()), err
}

func (s NitrousBinlogEvent) String() string {
	str, _ := text.Marshal(0xd484e90b6960c0da, capnp.Struct(s))
	return str
}

func (s NitrousBinlogEvent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NitrousBinlogEvent) DecodeFromPtr(p capnp.Ptr) NitrousBinlogEvent {
	return NitrousBinlogEvent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NitrousBinlogEvent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NitrousBinlogEvent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NitrousBinlogEvent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NitrousBinlogEvent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// NitrousBinlogEvent_List is a list of NitrousBinlogEvent.
type NitrousBinlogEvent_List = capnp.StructList[NitrousBinlogEvent]

// NewNitrousBinlogEvent creates a new list of NitrousBinlogEvent.
func NewNitrousBinlogEvent_List(s *capnp.Segment, sz int32) (NitrousBinlogEvent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[NitrousBinlogEvent](l), err
}

// NitrousBinlogEvent_Future is a wrapper for a NitrousBinlogEvent promised by a client call.
type NitrousBinlogEvent_Future struct{ *capnp.Future }

func (p NitrousBinlogEvent_Future) Struct() (NitrousBinlogEvent, error) {
	s, err := p.Future.Struct()
	return NitrousBinlogEvent(s), err
}

const schema_8cfb90d81c574cef = "x\xda\x12ps`1\xe4\xdd\xcf\xc8\xc0\x14(\xc2\xca" +
	"\xf6\xff\xd6\x81\x84L\xee\x97-W\x18\x04\xb5\x19\xff\xbf" +
	"\xf7\x09\x97\xb91\xe1w\x0f\x03\x0b;\x03\x83\xe1\xd1O" +
	"\x8c\x82\x0f\xd9\x19\xf4\xff\x87\x16\xa7\x16\x15\xeb\xe7\xe6\xb3" +
	"ed\x96\x14\xa5\xa6\xa4T\xea\x17\xa5V\xa4\x16\xe9\x17" +
	"\x14\xe5\x97\xe4\xeb\xe7e\x96\x14\xe5\x97\x16\xeb%'\x16" +
	"\xe4\x15X\xf9AxN\x99y9\xf9\xe9\xf2\xaee\xa9" +
	"y%\x01\x8c\x8c\x80\x00\x00\x00\xff\xff\x8a6*d"

func init() {
	schemas.Register(schema_8cfb90d81c574cef,
		0xd484e90b6960c0da)
}
