// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'container': string;
  'jump': string;
  'pancake': string;
}
export const cssExports: CssExports;
export default cssExports;
