// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dateControl': string;
  'title': string;
  'titleSection': string;
}
export const cssExports: CssExports;
export default cssExports;
