// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatarText': string;
  'container': string;
  'divider': string;
  'documentation': string;
  'leftNav': string;
  'menu': string;
  'rightNav': string;
}
export const cssExports: CssExports;
export default cssExports;
