// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: value.proto

package value

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Node:
	//	*PValue_Int
	//	*PValue_Double
	//	*PValue_Bool
	//	*PValue_String_
	//	*PValue_List
	//	*PValue_Dict
	//	*PValue_Table
	//	*PValue_Nil
	Node isPValue_Node `protobuf_oneof:"node"`
}

func (x *PValue) Reset() {
	*x = PValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PValue) ProtoMessage() {}

func (x *PValue) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PValue.ProtoReflect.Descriptor instead.
func (*PValue) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{0}
}

func (m *PValue) GetNode() isPValue_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (x *PValue) GetInt() int64 {
	if x, ok := x.GetNode().(*PValue_Int); ok {
		return x.Int
	}
	return 0
}

func (x *PValue) GetDouble() float64 {
	if x, ok := x.GetNode().(*PValue_Double); ok {
		return x.Double
	}
	return 0
}

func (x *PValue) GetBool() bool {
	if x, ok := x.GetNode().(*PValue_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *PValue) GetString_() string {
	if x, ok := x.GetNode().(*PValue_String_); ok {
		return x.String_
	}
	return ""
}

func (x *PValue) GetList() *PVList {
	if x, ok := x.GetNode().(*PValue_List); ok {
		return x.List
	}
	return nil
}

func (x *PValue) GetDict() *PVDict {
	if x, ok := x.GetNode().(*PValue_Dict); ok {
		return x.Dict
	}
	return nil
}

func (x *PValue) GetTable() *PVTable {
	if x, ok := x.GetNode().(*PValue_Table); ok {
		return x.Table
	}
	return nil
}

func (x *PValue) GetNil() *PVNil {
	if x, ok := x.GetNode().(*PValue_Nil); ok {
		return x.Nil
	}
	return nil
}

type isPValue_Node interface {
	isPValue_Node()
}

type PValue_Int struct {
	Int int64 `protobuf:"varint,1,opt,name=Int,proto3,oneof"`
}

type PValue_Double struct {
	Double float64 `protobuf:"fixed64,2,opt,name=Double,proto3,oneof"`
}

type PValue_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=Bool,proto3,oneof"`
}

type PValue_String_ struct {
	String_ string `protobuf:"bytes,4,opt,name=String,proto3,oneof"`
}

type PValue_List struct {
	List *PVList `protobuf:"bytes,5,opt,name=List,proto3,oneof"`
}

type PValue_Dict struct {
	Dict *PVDict `protobuf:"bytes,6,opt,name=Dict,proto3,oneof"`
}

type PValue_Table struct {
	Table *PVTable `protobuf:"bytes,7,opt,name=Table,proto3,oneof"`
}

type PValue_Nil struct {
	Nil *PVNil `protobuf:"bytes,8,opt,name=Nil,proto3,oneof"` // [deprecated] PVTuple Tuple = 9;
}

func (*PValue_Int) isPValue_Node() {}

func (*PValue_Double) isPValue_Node() {}

func (*PValue_Bool) isPValue_Node() {}

func (*PValue_String_) isPValue_Node() {}

func (*PValue_List) isPValue_Node() {}

func (*PValue_Dict) isPValue_Node() {}

func (*PValue_Table) isPValue_Node() {}

func (*PValue_Nil) isPValue_Node() {}

type PVList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*PValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *PVList) Reset() {
	*x = PVList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVList) ProtoMessage() {}

func (x *PVList) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVList.ProtoReflect.Descriptor instead.
func (*PVList) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{1}
}

func (x *PVList) GetValues() []*PValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type PVDict struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[string]*PValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PVDict) Reset() {
	*x = PVDict{}
	if protoimpl.UnsafeEnabled {
		mi := &file_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVDict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVDict) ProtoMessage() {}

func (x *PVDict) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVDict.ProtoReflect.Descriptor instead.
func (*PVDict) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{2}
}

func (x *PVDict) GetValues() map[string]*PValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type PVTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*PVDict `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *PVTable) Reset() {
	*x = PVTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVTable) ProtoMessage() {}

func (x *PVTable) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVTable.ProtoReflect.Descriptor instead.
func (*PVTable) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{3}
}

func (x *PVTable) GetRows() []*PVDict {
	if x != nil {
		return x.Rows
	}
	return nil
}

type PVNil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PVNil) Reset() {
	*x = PVNil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVNil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVNil) ProtoMessage() {}

func (x *PVNil) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVNil.ProtoReflect.Descriptor instead.
func (*PVNil) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{4}
}

var File_value_proto protoreflect.FileDescriptor

var file_value_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01,
	0x0a, 0x06, 0x50, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x49, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x49, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x06,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x06,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x56, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x56, 0x44, 0x69, 0x63, 0x74, 0x48, 0x00, 0x52, 0x04,
	0x44, 0x69, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x56, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x4e, 0x69, 0x6c, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x56, 0x4e, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x03, 0x4e,
	0x69, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x06, 0x50, 0x56,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x79, 0x0a, 0x06, 0x50, 0x56, 0x44, 0x69, 0x63, 0x74, 0x12,
	0x2b, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x50, 0x56, 0x44, 0x69, 0x63, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x42, 0x0a, 0x0b,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x26, 0x0a, 0x07, 0x50, 0x56, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x56, 0x44, 0x69,
	0x63, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x50, 0x56, 0x4e, 0x69,
	0x6c, 0x42, 0x12, 0x5a, 0x10, 0x66, 0x65, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x6c, 0x69, 0x62, 0x2f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_value_proto_rawDescOnce sync.Once
	file_value_proto_rawDescData = file_value_proto_rawDesc
)

func file_value_proto_rawDescGZIP() []byte {
	file_value_proto_rawDescOnce.Do(func() {
		file_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_value_proto_rawDescData)
	})
	return file_value_proto_rawDescData
}

var file_value_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_value_proto_goTypes = []interface{}{
	(*PValue)(nil),  // 0: PValue
	(*PVList)(nil),  // 1: PVList
	(*PVDict)(nil),  // 2: PVDict
	(*PVTable)(nil), // 3: PVTable
	(*PVNil)(nil),   // 4: PVNil
	nil,             // 5: PVDict.ValuesEntry
}
var file_value_proto_depIdxs = []int32{
	1, // 0: PValue.List:type_name -> PVList
	2, // 1: PValue.Dict:type_name -> PVDict
	3, // 2: PValue.Table:type_name -> PVTable
	4, // 3: PValue.Nil:type_name -> PVNil
	0, // 4: PVList.values:type_name -> PValue
	5, // 5: PVDict.values:type_name -> PVDict.ValuesEntry
	2, // 6: PVTable.rows:type_name -> PVDict
	0, // 7: PVDict.ValuesEntry.value:type_name -> PValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_value_proto_init() }
func file_value_proto_init() {
	if File_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVDict); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVNil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_value_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PValue_Int)(nil),
		(*PValue_Double)(nil),
		(*PValue_Bool)(nil),
		(*PValue_String_)(nil),
		(*PValue_List)(nil),
		(*PValue_Dict)(nil),
		(*PValue_Table)(nil),
		(*PValue_Nil)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_value_proto_goTypes,
		DependencyIndexes: file_value_proto_depIdxs,
		MessageInfos:      file_value_proto_msgTypes,
	}.Build()
	File_value_proto = out.File
	file_value_proto_rawDesc = nil
	file_value_proto_goTypes = nil
	file_value_proto_depIdxs = nil
}
