config:
  aws:profile: admin
  aws:region: us-west-2
  configs:cache-conf:
    primary:
      secure: AAABAOVXjzi9gTxx9DQKpiN1KLe62VK7nVhEjpz7IpromgyAXMTzSEnOOtrykUxB5Vyts3N2XPxh1S4Yw4hO+/w45X23XeoRJUUZMvaCgH1CHHccOGV9Xa0c8Phjj2YkQQ==
    replica:
      secure: AAABAMTMmU6f5hmaWY60+/LrHjac8JY1F+KcIoLBKNWISz7plQxdYQmgWZAXXYd5SL3OzvM9GziY5d9BymdNYMMvZCebWHZKfaT3fuAKQmjk9FcFm/t273oWUyFIjfdMwg8=
  configs:db-conf:
    db:
      secure: AAABAGTofRizXL9/oApUavNzdF8rAr12RLOkEmTYdkZ8FmyDW0Y=
    host:
      secure: AAABAJ93KrArnufIwS1Vmnuh2WnI01maQAqYtzvXarVohEAr1wQBBtLSgqZco5zHZJ3PhkV25Zg6gp5QWNXbw/E=
    password:
      secure: AAABACF1ocZYBGSlpIsaYBONLK+QlKYkvuyzem0AWiQvVxOtRSkJY/ZrjaKiJfs3uSF3KZACdlzDF2nYFEvwyxE4De3rBFRFe0WVnUl3X4jEVM9HUg==
    username:
      secure: AAABABgSvmqvIzfLeNdzeatWGdobLzRdF4WrwVv6oAc5awyMZfcpCk870jU=
  configs:kafka-conf:
    password:
      secure: AAABAIbdM4rB2+1NX+gNhK01aNAHXyzSEUyQUS8Nm3QhqbxY1rsbvaeWn5csL8jXhape2pDRlyP4VMS3blnZnbV976KQ6AxDX7SH5sn71caPBgE4xjoG6F5B5sQ5xza2
    server:
      secure: AAABAKJtpAGDbadKC9q4heRYTs+1wa7oGgTxqECjwi5RqfXiVYVcohnKkcWivwnjzJm6h9TsR+gXbAdKCaCJVu6VG3L4mFjgzlDc7A==
    username:
      secure: AAABAA7+HpYiJgQslJMJG79MG24E3yPHGKrYfukgec9GBE0gBc3U4pdPPVe5+v1A
  configs:redis-conf:
    addr:
      secure: AAABAI2/SEzv6GHUvfsEQG6qd7NeaeGTrBZUOcsywkUxpAzqmgEKiVWdQBRYWihHL94NuJHZsGtxAILLLocML2Bx7Btto+slcrF27Uul9EGMhX95juL07hV7Jv7Wbolu8tuwvZmpXLs=
  configs:tier-conf:
    tier_id: "100"
