---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-io1
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
  fsType: ext4
