// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aggregate': string;
  'aggregateList': string;
  'subtitle': string;
  'tag': string;
  'tags': string;
  'titleIcon': string;
  'titleLhs': string;
  'versionDropdownIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
