// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputContainer': string;
  'inputSuggestions': string;
  'prefixContainer': string;
  'selectedFilter': string;
  'suggestion': string;
  'unselectIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
