# This is a basic workflow to help you get started with Actions

name: e2e-tests-staging-linux-x64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64, e2e-tests]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2  
        with:
          path: rexer-pyclient-alpha	
          repository: fennel-ai/rexer-pyclient-alpha
          token: ${{ secrets.ACCESS_TOKEN }}

      # Move the repo explicitly, sadly github actions doesn't support this by default..
      # https://github.com/actions/checkout/issues/197#issuecomment-829560171
      - run: mv rexer-pyclient-alpha ../rexer-pyclient-alpha

      # Install prerequisites
      - name: install build essential and pkg-config
        run: |
          sudo apt-get --assume-yes install build-essential

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install and configure poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Install rexer which will be used later in the e2etest_staging.py
      - name: Install dependencies using poetry
        working-directory: ../rexer-pyclient-alpha
        run: poetry install --no-interaction

      # Run the test
      - name: Run test
        env:
          FENNEL_ROOT: ${{ github.workspace }}
        working-directory: ../rexer-pyclient-alpha
        run: |
          poetry run python -m unittest discover ../../rexer/e2etests -p "teste2e_staging.py"

      # Remove the client directory. Github actions removes the one installed using `actions/checkout@v2` which is now empty since we moved the content
      - name: Remove rexer-client dir
        run: |
          sudo rm -rf ../rexer-pyclient-alpha
