# This is a basic workflow to help you get started with Actions

name: integration-tests-linux-x64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "integration"
  integration:
    name: integration
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64, integration-tests]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install build essentials
      - name: install build essential
        run: sudo apt-get --assume-yes install build-essential

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          path: rexer-pyclient-alpha
          repository: fennel-ai/rexer-pyclient-alpha
          token: ${{ secrets.ACCESS_TOKEN }}

      # Move the repo explicitly, sadly github actions doesn't support this by default..
      # https://github.com/actions/checkout/issues/197#issuecomment-829560171
      - run: mv rexer-pyclient-alpha ../rexer-pyclient-alpha

      # Install go (we use 1.18 version, so we will stick to it)
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: run go integration tests
        env:
          KAFKA_SERVER_ADDRESS: ${{ secrets.KAFKA_SERVER_ADDRESS }}
          KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
          MSK_KAFKA_SERVER_ADDRESS: ${{ secrets.MSK_KAFKA_SERVER_ADDRESS }}
          MSK_KAFKA_USERNAME: ${{ secrets.MSK_KAFKA_USERNAME }}
          MSK_KAFKA_PASSWORD: ${{ secrets.MSK_KAFKA_PASSWORD }}
          MYSQL_SERVER_ADDRESS: ${{ secrets.MYSQL_SERVER_ADDRESS }}
          MYSQL_DATABASE_NAME: ${{ secrets.MYSQL_DATABASE_NAME }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          REDIS_SERVER_ADDRESS: ${{ secrets.REDIS_SERVER_ADDRESS }}
          CACHE_PRIMARY: ${{ secrets.CACHE_PRIMARY }}
          TIER_ID: ${{ secrets.TIER_ID }}
          PLANE_ID: ${{ secrets.PLANE_ID }}
          BADGER_DIR: ${{ secrets.BADGER_DIR }}
        run: |
          cd go/fennel
          go test -v -tags integration ./... -count 1

     # Remove the client directory. Github actions removes the one installed using `actions/checkout@v2` which is now empty since we moved the content
      - name: Remove rexer-client dir
        if: always()
        run: |
          sudo rm -rf ../rexer-pyclient-alpha
