# This is a basic workflow to help you get started with Actions

name: unit-tests-linux-x64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Assumes that the remote machine has nix installed in it already.
      
      # Setup nix by changing into the directory
      - name: enable nix shell
        run: |
          export INSTALL_PULUMI=false
          nix-shell

      # Runs the unit tests 
      - name: run fennel go unit tests
        run: |
          cd go/fennel
          go test -v ./...
