# This is a basic workflow to help you get started with Actions

name: unit-tests-linux-x64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows running unit test on every pull request
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install build essentials
      - name: install build essential
        run: sudo apt-get --assume-yes install build-essential

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install go (we use 1.17.0 version, so we will stick to it)
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      # -count 1 is required to force override test caches
      - name: run go unit tests
        run: |
          cd go/fennel
          go test -v -p 5 ./... -count 1
