# This is a basic workflow to help you get started with Actions

name: unit-tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install nix on the remote machine
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
      
      - name: install and run direnv
        run: |
          sudo apt get install direnv
          direnv allow .

      # Runs the unit tests 
      - name: run fennel go unit tests
        run: |
          cd go/fennel
          go test -v ./...
