# This is a basic workflow to help you get started with Actions

name: unit-tests-linux-x64

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DISABLE_PULUMI: true
  NIX_PATH: channel:nixos-unstable

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install python - this is required to install and run nix.
      # Nix will however install a version specified in our codebase and run the tests using it.
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        continue-on-error: true

      - run: nix-shell --run "echo OK"
      - run: nix-shell
      
      - name: run the tests
        run: |
          nix-shell
          cd go/fennel
          which go
